# Generated by Django 4.1.7 on 2023-03-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_servidor', models.CharField(choices=[('G', 'gmail.com'), ('Y', 'yahoo.com'), ('H', 'hotmail.com'), ('N', 'Nenhuma das opções')], max_length=1, verbose_name='Servidor de E-mail')),
            ],
        ),
    ]
