# Generated by Django 4.1.7 on 2023-03-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_data_nascimento_home_email_home_nome_home_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='foto_usuario',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
