# Generated by Django 4.2.1 on 2023-06-12 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0004_alter_mymeeting_mymeeting_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFeedback',
            fields=[
                ('myfeedback_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('myfeedback_host', models.CharField(max_length=100)),
                ('myfeedback_guest', models.CharField(max_length=100)),
                ('myfeedback_question1', models.CharField(max_length=300)),
                ('myfeedback_answer1', models.CharField(max_length=300)),
                ('myfeedback_question2', models.CharField(max_length=300)),
                ('myfeedback_answer2', models.CharField(max_length=300)),
                ('myfeedback_question3', models.CharField(max_length=300)),
                ('myfeedback_answer3', models.CharField(max_length=300)),
                ('myfeedback_classification', models.IntegerField(default=0)),
                ('myfeedback_cad_hour', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('myfeedback_meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.mymeeting')),
            ],
        ),
    ]
