# Generated by Django 4.2.1 on 2023-06-12 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyPdi',
            fields=[
                ('mypdi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mypdi_host', models.CharField(max_length=100)),
                ('mypdi_guest', models.CharField(max_length=100)),
                ('mypdi_area', models.CharField(max_length=100)),
                ('mypdi_office', models.CharField(max_length=300)),
                ('mypdi_admission', models.DateField(blank=True)),
                ('mypdi_obj_short_term', models.CharField(max_length=300)),
                ('mypdi_obj_short_date', models.DateField(blank=True)),
                ('mypdi_obj_mid_term', models.CharField(max_length=300)),
                ('mypdi_obj_mid_date', models.DateField(blank=True)),
                ('mypdi_obj_long_term', models.CharField(max_length=300)),
                ('mypdi_obj_long_date', models.DateField(blank=True)),
                ('mypdi_obj_strong_points', models.CharField(max_length=300)),
                ('mypdi_obj_dev_points', models.CharField(max_length=300)),
                ('mypdi_action70', models.CharField(max_length=100)),
                ('mypdi_status70', models.CharField(choices=[('AG', 'Aguardando'), ('IN', 'Iniciada'), ('FI', 'Finalizada')], max_length=2)),
                ('mypdi_action20', models.CharField(max_length=100)),
                ('mypdi_status20', models.CharField(choices=[('AG', 'Aguardando'), ('IN', 'Iniciada'), ('FI', 'Finalizada')], max_length=2)),
                ('mypdi_action10', models.CharField(max_length=100)),
                ('mypdi_status10', models.CharField(choices=[('AG', 'Aguardando'), ('IN', 'Iniciada'), ('FI', 'Finalizada')], max_length=2)),
                ('mypdi_status_gobal', models.CharField(choices=[('AG', 'Aguardando'), ('IN', 'Iniciada'), ('FI', 'Finalizada')], max_length=2)),
                ('mypdi_main_goal', models.CharField(max_length=150)),
                ('mypdi_cad_hour', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
