# Generated by Django 4.2.1 on 2023-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypdi',
            old_name='mypdi_action10',
            new_name='mypdi_action_1',
        ),
        migrations.RenameField(
            model_name='mypdi',
            old_name='mypdi_action20',
            new_name='mypdi_action_10',
        ),
        migrations.RenameField(
            model_name='mypdi',
            old_name='mypdi_action70',
            new_name='mypdi_action_2',
        ),
        migrations.RenameField(
            model_name='mypdi',
            old_name='mypdi_admission',
            new_name='mypdi_date_admission',
        ),
        migrations.RenameField(
            model_name='mypdi',
            old_name='mypdi_obj_dev_points',
            new_name='mypdi_dev_points',
        ),
        migrations.RenameField(
            model_name='mypdi',
            old_name='mypdi_status10',
            new_name='mypdi_status_1',
        ),
        migrations.RenameField(
            model_name='mypdi',
            old_name='mypdi_status20',
            new_name='mypdi_status_10',
        ),
        migrations.RenameField(
            model_name='mypdi',
            old_name='mypdi_status70',
            new_name='mypdi_status_2',
        ),
        migrations.RenameField(
            model_name='mypdi',
            old_name='mypdi_obj_long_term',
            new_name='mypdi_strong_points',
        ),
        migrations.RemoveField(
            model_name='mypdi',
            name='mypdi_obj_long_date',
        ),
        migrations.RemoveField(
            model_name='mypdi',
            name='mypdi_obj_mid_date',
        ),
        migrations.RemoveField(
            model_name='mypdi',
            name='mypdi_obj_mid_term',
        ),
        migrations.RemoveField(
            model_name='mypdi',
            name='mypdi_obj_short_date',
        ),
        migrations.RemoveField(
            model_name='mypdi',
            name='mypdi_obj_short_term',
        ),
        migrations.RemoveField(
            model_name='mypdi',
            name='mypdi_obj_strong_points',
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_5',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_6',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_7',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_8',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_9',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_time_1',
            field=models.CharField(choices=[('ST', 'Curto Prazo'), ('MD', 'Medio Prazo'), ('LG', 'Longo Prazo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_time_10',
            field=models.CharField(choices=[('ST', 'Curto Prazo'), ('MD', 'Medio Prazo'), ('LG', 'Longo Prazo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_time_2',
            field=models.CharField(choices=[('ST', 'Curto Prazo'), ('MD', 'Medio Prazo'), ('LG', 'Longo Prazo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_time_3',
            field=models.CharField(choices=[('ST', 'Curto Prazo'), ('MD', 'Medio Prazo'), ('LG', 'Longo Prazo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_time_4',
            field=models.CharField(choices=[('ST', 'Curto Prazo'), ('MD', 'Medio Prazo'), ('LG', 'Longo Prazo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_time_5',
            field=models.CharField(choices=[('ST', 'Curto Prazo'), ('MD', 'Medio Prazo'), ('LG', 'Longo Prazo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_time_6',
            field=models.CharField(choices=[('ST', 'Curto Prazo'), ('MD', 'Medio Prazo'), ('LG', 'Longo Prazo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_time_7',
            field=models.CharField(choices=[('ST', 'Curto Prazo'), ('MD', 'Medio Prazo'), ('LG', 'Longo Prazo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_time_8',
            field=models.CharField(choices=[('ST', 'Curto Prazo'), ('MD', 'Medio Prazo'), ('LG', 'Longo Prazo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_time_9',
            field=models.CharField(choices=[('ST', 'Curto Prazo'), ('MD', 'Medio Prazo'), ('LG', 'Longo Prazo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_type_1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_type_10',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_type_2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_type_3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_type_4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_type_5',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_type_6',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_type_7',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_type_8',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_action_type_9',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_status_3',
            field=models.CharField(choices=[('AG', 'Aguardando'), ('IN', 'Iniciada'), ('FI', 'Finalizada')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_status_4',
            field=models.CharField(choices=[('AG', 'Aguardando'), ('IN', 'Iniciada'), ('FI', 'Finalizada')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_status_5',
            field=models.CharField(choices=[('AG', 'Aguardando'), ('IN', 'Iniciada'), ('FI', 'Finalizada')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_status_6',
            field=models.CharField(choices=[('AG', 'Aguardando'), ('IN', 'Iniciada'), ('FI', 'Finalizada')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_status_7',
            field=models.CharField(choices=[('AG', 'Aguardando'), ('IN', 'Iniciada'), ('FI', 'Finalizada')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_status_8',
            field=models.CharField(choices=[('AG', 'Aguardando'), ('IN', 'Iniciada'), ('FI', 'Finalizada')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypdi',
            name='mypdi_status_9',
            field=models.CharField(choices=[('AG', 'Aguardando'), ('IN', 'Iniciada'), ('FI', 'Finalizada')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
