# Generated by Django 4.2.1 on 2023-05-30 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyMeeting',
            fields=[
                ('mymeeting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mymeeting_host', models.CharField(max_length=100)),
                ('mymeeting_guest', models.CharField(max_length=100)),
                ('mymeeting_title', models.CharField(max_length=100)),
                ('mymeeting_schedule', models.CharField(max_length=300)),
                ('mymeeting_place', models.CharField(max_length=100)),
                ('mymeeting_link', models.CharField(max_length=300)),
                ('mymeeting_status', models.CharField(choices=[('AB', 'Aberta'), ('EN', 'Encerrada')], max_length=2)),
                ('mymeeting_date', models.DateField(blank=True)),
                ('mymeeting_hour', models.TimeField(blank=True)),
                ('mymeeting_cad_hour', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
