# Generated by Django 4.2.1 on 2023-05-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymeeting',
            name='mymeeting_link',
            field=models.URLField(max_length=300),
        ),
    ]
