# Generated by Django 4.2.1 on 2023-06-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_alter_mymeeting_mymeeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymeeting',
            name='mymeeting_room',
            field=models.URLField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mymeeting',
            name='mymeeting_place',
            field=models.CharField(choices=[('PRE', 'Presencial'), ('ONL', 'On-line')], max_length=3),
        ),
    ]
