# Generated by Django 4.2.1 on 2023-06-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_mymeeting_mymeeting_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymeeting',
            name='mymeeting_room',
            field=models.CharField(max_length=100),
        ),
    ]
