# Generated by Django 4.2.7 on 2023-11-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Código gerado para redirecionamento.', max_length=100, verbose_name='código')),
                ('date', models.DateTimeField(help_text='Data em que o checkout foi realizado.', verbose_name='Data')),
                ('success', models.BooleanField(db_index=True, default=False, help_text='O checkout foi feito com sucesso?', verbose_name='Sucesso')),
                ('message', models.TextField(blank=True, help_text='Mensagem apresentada no caso de erro no checkout.', verbose_name='Mensagem de erro')),
            ],
            options={
                'verbose_name': 'Checkout',
                'verbose_name_plural': 'Checkouts',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='O código da transação.', max_length=100, unique=True, verbose_name='código')),
                ('reference', models.CharField(blank=True, db_index=True, help_text='A referência passada na transação.', max_length=200, verbose_name='referência')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_analise', 'Em análise'), ('pago', 'Pago'), ('disponivel', 'Disponível'), ('em_disputa', 'Em disputa'), ('devolvido', 'Devolvido'), ('cancelado', 'Cancelado')], db_index=True, help_text='Status atual da transação.', max_length=20, verbose_name='Status')),
                ('date', models.DateTimeField(help_text='Data em que a transação foi criada.', verbose_name='Data')),
                ('last_event_date', models.DateTimeField(help_text='Data da última alteração na transação.', verbose_name='Última alteração')),
                ('content', models.TextField(help_text='Transação no formato json.', verbose_name='Transação')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_analise', 'Em análise'), ('pago', 'Pago'), ('disponivel', 'Disponível'), ('em_disputa', 'Em disputa'), ('devolvido', 'Devolvido'), ('cancelado', 'Cancelado')], help_text='Status da transação.', max_length=20, verbose_name='Status')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkouts.transaction', verbose_name='Transação')),
            ],
            options={
                'verbose_name': 'Histórico da transação',
                'verbose_name_plural': 'Históricos de transações',
                'ordering': ['date'],
            },
        ),
    ]
