# Generated by Django 4.2.7 on 2023-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paymentLink',
            field=models.CharField(blank=True, help_text='Link de geração do boleto.', max_length=255, verbose_name='link'),
        ),
    ]
