# Generated by Django 4.2.7 on 2023-12-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('area_code', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=120)),
                ('cpf', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(max_length=120)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('complement', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
            ],
        ),
    ]
